### ISSUE TITLE
Unable to translate devise mails

### ISSUE THREAD

**Issue by Kagemaru** [mainio/decidim-module-term_customizer#93]
**Steps to reproduce**

1. Generate development_app
2. Update `config/locales/en.yml` with:
   ```yaml
   devise:
     mailer:
       confirmation_instructions:
         subject: "Base Subject"
   ```
3. Create Translation with:
   Translation key: `devise.mailer.confirmation_instructions.subject`
   Customized term: `Overriden Subject`
4. Register a new user and get the confirmation mail

**Expected Result**
Get `Overriden Subject` as subject

**Actual Result**
Get `Base Subject` as subject
